service: serverless-chat-app-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - cognito-idp:AdminCreateUser
        - cognito-idp:AdminConfirmSignUp
      Resource: "*"

functions:
  registerUser:
    handler: function/registerUser.handler
    events:
      - http:
          path: register
          method: post
          cors: true

plugins:
  - serverless-appsync-plugin

custom:
  appSync:
    name: chatAppAppSync
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      userPoolId:
        Ref: UserPool
      awsRegion: ${self:provider.region}
      defaultAction: ALLOW
    mappingTemplatesLocation: resolvers
    mappingTemplates:
      - dataSource: UserTable
        type: Query
        field: getUserById
      - dataSource: UserTable
        type: Query
        field: getAllUsers
      - dataSource: UserTable
        type: Mutation
        field: deleteUser
      - dataSource: UserTable
        type: Mutation
        field: updateUser
      - dataSource: MessageTable
        type: Query
        field: getAllMessages
      - dataSource: MessageTable
        type: Mutation
        field: createMessage
    additionalAuthenticationProviders:
      - authenticationType: AWS_IAM
    dataSources:
      - type: AMAZON_DYNAMODB
        name: UserTable
        config:
          tableName: chatAppUserTable
      - type: AMAZON_DYNAMODB
        name: MessageTable
        config:
          tableName: chatAppMessageTable

resources:
  Resources:
    UserTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: chatAppUserTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    MessageTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: chatAppMessageTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: chatAppUsers
        Policies:
          PasswordPolicy:
            MinimumLength: 6
            RequireLowercase: false
            RequireNumbers: false
            RequireSymbols: false
            RequireUppercase: false
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: false

    UserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        UserPoolId:
          Ref: UserPool
        ClientName: chat-app-client
        GenerateSecret: false
